language: node_js
node_js:
  - stable
deploy:
  provider: npm
  on:
    tags: true
  email:
    secure: EBCegLo0q98yjlquJd+bNmi4b9rUia54hGHFyrA4f1t3AswKfsiPFivCk9xqLh6gwzQZzQhoCUVRFEsRnxGgcMQwJtC+kULY3Yz+u08lJXgGCWG1yBsiPN36oeJbGPXaBQXantLN9S8CIjNsrO0S8LTHCz5Q8KSTbaxptZeg0LELaNJSqVHu0+V6THkx+9icUogEe20AOMsKoss7gLIzZZJgEVUnkncoIQUKC5PDhKXi+o9oSs92tqFsjMGkJxCoC8yfc0XrswFAhkbenIL0VGHK7V4lzWbPUms/rabhYAdsk99yMFkuQug1QFgFsIikt4gyXwhYye3a9MFVqp6aGgkzixn5xTTbwFeyusEH0Jcjzs1rpoO7Vqk41fDGU8Cy6IvQzf9wLgsOKbM+wEwN5/5Xt3QqViK8FJ7YUcvMgMwgcOJP3Bri3pu5yAHQtW/loSqGD0pvdJztNssJU0J83f32J5Fqn8LR3lSbXu8FkBXUUkaFPgyoiFk/3ywCR5YplkzfLwQf+ilW0+nWbYsj/RiGZj6wCatdLUy9itlsEIAh5CsFC2E9Q1/dhr8BNsspc5es88SP4Oqa2tnOkPT0Gr3DKqOD6egGJAJLEura1h1I3ny9tAeEkjo4FscyNIxkzVP0u4tChf2p767xPYBOThQNjYZUEImMWWU/dzksHHg=
  api_key:
    secure: AYimXKIMuEdy0EoHY0SR3KWY7lQjhtSs2talZ1eueYcAl8+ot/gqj93jcPpaNQnBTohML4jdoxWfFrpkBOpgQe6yjqhVJQDDOz7KhptcPQNLwv2DJnpraqVavlZ8DglbuJ9DXTpZpS7BJxCr1pOQ5RrdGqhpcguJuPvbcqvs6dlxEtdIepBYa7z9KI/fQlpdyZ5qpP0GrqKgDSaFaXQWIRTmAPx1lYtz6OphrAtIbTkgEx+ZSKp9y4tyK1Q+R2IDmc7Pn7harYf7lxuzSOBscn3c6AW+Rudmh5PSDBUk0Xx3sA57DmZ7xsfI3jb70n3UF3jum/w8vsTRMnV4yuFpn0XbhALJUn8YRsLhmvqcg6wXxaOBTw0qCZDP/BySUegJAyNqDJkEHbtDykwchJQZn4dN9HRTuo33a/oJtBkQbIxmUF8HkyD2A7IQ+x4rZ3FUZoDDqT0AXAKz5ZVjlS8GxSh1rN/VSTZxMjdAMuNX6Ut2eoHGcSVuyp/RsWcMjScBxulBKfIH1+UlPORhPtTj8arBPXV/LHdaAkSziztxDXY3BOG58dR15T+2BpQVH92maUKMGSva92/mm2M5FEpNZ3oovZGpjiIqwTkB1csX61xhwhO32D6DY02aupuQjduYxlqBrGcfrnJKcSbIgf4fPHXISDtiPI9WYzJFF3qEqBM=
  skip_cleanup: true
